Repository enjin/platform-ui, pull requests merged in 2024-04, with the labels that each got.

#88 [PLA-1701] UI improvements
  package-lock.json
  package.json
  resources/js/components/Address.vue
  resources/js/components/App.vue
  resources/js/components/CollapseCard.vue
  resources/js/components/CopyTextIcon.vue
  resources/js/components/FormInput.vue
  resources/js/components/FormList.vue
  resources/js/components/FormSelect.vue
  resources/js/components/MultiCheckbox.vue
  resources/js/components/ProfileMenu.vue
  resources/js/components/RichTextEditor.vue
  resources/js/components/SideNavbar.vue
  resources/js/components/SupportButton.vue
  resources/js/components/TokenIdInput.vue
  resources/js/components/Tooltip.vue
  resources/js/components/UserNavbar.vue
  resources/js/components/batch/BatchMint.vue
  resources/js/components/batch/BatchSetAttribute.vue
  resources/js/components/batch/BatchTransfer.vue
  resources/js/components/batch/forms/BatchMintForm.vue
  resources/js/components/batch/forms/BatchTransferForm.vue
  resources/js/components/beam/ClaimableTokenForm.vue
  resources/js/components/fueltank/DispatchRuleForm.vue
  resources/js/components/pages/create/CreateBatch.vue
  resources/js/components/pages/create/CreateBeam.vue
  resources/js/components/pages/create/CreateCollection.vue
  resources/js/components/pages/create/CreateFuelTank.vue
  resources/js/components/pages/create/CreateListing.vue
  resources/js/components/pages/create/CreateToken.vue
  resources/js/components/slideovers/collection/MutateCollectionSlideover.vue
  resources/js/components/slideovers/token/DetailsTokenSlideover.vue
  resources/js/components/slideovers/token/MintTokenSlideover.vue
  resources/js/components/slideovers/token/MutateTokenSlideover.vue
  resources/js/types/types.enums.ts
  resources/js/util/index.ts
  resources/js/util/marked.ts
  tailwind.config.js
Labels: documentation, enhancement, Review effort [1-5]: 4

#90 [PLA-1714] Add refresh csrf token
  resources/js/api/index.ts
  resources/js/components/pages/Settings.vue
  resources/js/store/index.ts
Labels: enhancement, Review effort [1-5]: 2

#92 [PLA-1702] handle error throttle
  resources/js/components/pages/auth/ResetPassword.vue
  resources/js/store/index.ts
Labels: enhancement, Review effort [1-5]: 2, bug_fix

#91 [PLA-1707] update transaction status
  resources/js/components/ConfirmModal.vue
  resources/js/components/pages/SettingsResetPassword.vue
  resources/js/components/pages/Transactions.vue
Labels: enhancement, Review effort [1-5]: 3, bug_fix

#93 hotfix: ts-fix
  resources/js/components/fueltank/DispatchRuleForm.vue
  resources/js/store/transaction.ts
Labels: enhancement, Review effort [1-5]: 2

#97 [PLA-1727] Update recaptcha logic
  resources/js/api/auth.ts
  resources/js/components/pages/auth/Login.vue
  resources/js/components/pages/auth/Register.vue
  resources/js/components/pages/auth/RequestResetPassword.vue
  resources/js/graphql/mutation/auth/RegisterUser.ts
  resources/js/graphql/mutation/auth/RequestPasswordReset.ts
  resources/js/graphql/query/auth/Login.ts
  resources/js/store/index.ts
  resources/views/app.blade.php
Labels: enhancement, Bug fix, Review effort [1-5]: 2

#98 [PLA-1727] fix login query
  resources/js/graphql/query/auth/Login.ts
Labels: Bug fix, Review effort [1-5]: 2

#100 [PLA-1736] fix recaptcha loading
  resources/js/components/pages/auth/Login.vue
  resources/js/components/pages/auth/Register.vue
  resources/js/components/pages/auth/RequestResetPassword.vue
Labels: enhancement, Review effort [1-5]: 2, bug_fix

#101 [PLA-1728] add optional recaptcha
  resources/js/api/auth.ts
  resources/js/api/mutations.ts
  resources/js/api/queries.ts
  resources/js/graphql/mutation/auth/RegisterUser.ts
  resources/js/graphql/mutation/auth/RegisterUserRecaptcha.ts
  resources/js/graphql/mutation/auth/RequestPasswordResetRecaptcha.ts
  resources/js/graphql/query/auth/Login.ts
  resources/js/graphql/query/auth/LoginRecaptcha.ts
Labels: enhancement, Review effort [1-5]: 3

#99 [PLA-1417] Add dusk id
  resources/js/components/CollapseCard.vue
  resources/js/components/NotificationsList.vue
  resources/js/components/ProfileMenu.vue
  resources/js/components/batch/BatchMint.vue
  resources/js/components/pages/Collections.vue
  resources/js/components/pages/Settings.vue
  resources/js/components/pages/SettingsResetPassword.vue
  resources/js/components/pages/Tokens.vue
  resources/js/components/pages/auth/Register.vue
  resources/js/components/pages/create/CreateCollection.vue
  resources/js/components/pages/create/CreateToken.vue
Labels: enhancement, Review effort [1-5]: 2

#102 [PLA-1740] bad request 400 error handling
  resources/js/api/index.ts
  resources/js/components/batch/BatchMint.vue
  resources/js/components/pages/Collections.vue
  resources/js/components/pages/Settings.vue
  resources/js/components/pages/SettingsResetPassword.vue
  resources/js/components/pages/auth/RequestResetPassword.vue
  resources/js/components/pages/auth/ResetPassword.vue
  resources/js/graphql/mutation/auth/RequestPasswordReset.ts
  resources/js/store/index.ts
Labels: enhancement, Review effort [1-5]: 3, bug_fix
