Repository enjin/platform-ui, pull requests merged in 2024-06, with the labels that each got.

#118 [PLA-1809] fix sales page
  resources/js/components/marketplace/SalesList.vue
  resources/js/components/slideovers/marketplace/DetailsSaleSlideover.vue
  resources/js/graphql/query/marketplace/GetSales.ts
  resources/js/util/index.ts
Labels: Bug fix, Review effort [1-5]: 2

#119 [PLA-1779] fix darkmode ui
  resources/js/components/App.vue
  resources/js/components/SignTransaction.vue
  resources/js/components/slideovers/common/DetailsTransactionSlideover.vue
Labels: Bug fix, Review effort [1-5]: 2

#120 [PLA-1783] fix internal beams query
  resources/js/components/beam/BeamsList.vue
  resources/js/store/index.ts
Labels: Bug fix, Review effort [1-5]: 2

#124 [PLA-1793] fix fueltank creation options
  resources/js/components/pages/create/CreateBeam.vue
  resources/js/components/pages/create/CreateFuelTank.vue
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#123 [PLA-1824] fix token creation
  resources/js/components/pages/create/CreateCollection.vue
  resources/js/components/pages/create/CreateToken.vue
Labels: Bug fix, Review effort [1-5]: 2

#121 [PLA-1648] add token collection name
  resources/js/api/index.ts
  resources/js/components/pages/Collections.vue
  resources/js/components/pages/Tokens.vue
  resources/js/store/index.ts
Labels: enhancement, Review effort [1-5]: 4

#125 [PLA-1779] darkmode fixes
  resources/js/components/SupportButton.vue
  resources/js/components/beam/BeamsList.vue
  resources/js/components/pages/create/CreateCollection.vue
  resources/js/components/pages/create/CreateFuelTank.vue
  resources/js/components/pages/create/CreateToken.vue
  resources/js/components/slideovers/beam/ClaimBeamSlideover.vue
  resources/js/components/slideovers/beam/DetailsBeamSlideover.vue
  resources/js/components/slideovers/marketplace/DetailsListingSlideover.vue
  resources/js/graphql/query/GetCollectionIds.ts
Labels: enhancement, Bug fix, Review effort [1-5]: 2

#128 [PLA-1677] balance transfer
  resources/js/api/index.ts
  resources/js/components/UserNavbar.vue
  resources/js/components/pages/SettingsWalletAccount.vue
  resources/js/components/pages/auth/Login.vue
  resources/js/components/pages/auth/Register.vue
  resources/js/components/slideovers/common/TransferBalanceSlideover.vue
  resources/js/graphql/mutation/TransferBalance.ts
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#129 [PLA-1678] Laravel 11 update.
  .php-cs-fixer.php
  composer.json
  pint.json
Labels: enhancement, Review effort [1-5]: 2, configuration changes

#127 [PLA-1864] Remove csrf cookie meta and use cookie instead
  resources/js/api/index.ts
  resources/js/components/pages/Settings.vue
  resources/js/store/index.ts
  resources/views/app.blade.php
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#130 Revert "[PLA-1864] Remove csrf cookie meta and use cookie instead"
  resources/js/api/index.ts
  resources/js/components/pages/Settings.vue
  resources/js/store/index.ts
  resources/views/app.blade.php
Labels: enhancement, Bug fix, Review effort [1-5]: 3
