Repository enjin/platform-ui, pull requests merged in 2024-08, with the labels that each got.

#145 hotfix: fix user query
  resources/js/graphql/query/auth/User.ts
Labels: Bug fix, Review effort [1-5]: 1

#146 [PLA-1920] supply cap token
  resources/js/components/pages/create/CreateToken.vue
  resources/js/types/types.enums.ts
Labels: enhancement, Review effort [1-5]: 3

#144 [PLA-1916] fix notifications hover box
  resources/js/components/Popover.vue
Labels: Bug fix, Review effort [1-5]: 1

#147 [PLA-1925] add deposit fee
  resources/js/components/SignTransaction.vue
Labels: enhancement, Review effort [1-5]: 2

#148 [PLA-1911] fix collection tracking
  resources/js/components/App.vue
  resources/js/components/pages/Collections.vue
  resources/js/factory/collection.ts
  resources/js/store/connection.ts
Labels: enhancement, Bug fix, Review effort [1-5]: 2

#149 [PLA-1929] Removes defining process.env in vite configs.
  vite.config.laravel.ts
  vite.config.ts
Labels: bug, Bug fix, Review effort [1-5]: 1

#150 [PLA-1911] improve collection tracking check
  resources/js/components/App.vue
  resources/js/components/DropdownMenu.vue
  resources/js/components/TransactionResultChip.vue
  resources/js/components/pages/Collections.vue
  resources/js/factory/collection.ts
Labels: Bug fix, Review effort [1-5]: 2

#151 [PLA-1911] fix tracking with daemon account
  resources/js/factory/collection.ts
Labels: Bug fix, Review effort [1-5]: 2

#152 [PLA-1934] tracking snackbar
  resources/js/components/pages/Collections.vue
Labels: enhancement, Bug fix, Review effort [1-5]: 2

#153 [PLA-1936] fix metadata fetching
  resources/js/api/index.ts
  resources/js/components/pages/Collections.vue
  resources/js/components/pages/Tokens.vue
Labels: enhancement, Bug fix, Review effort [1-5]: 2

#154 [PLA-1940] fix name missing
  resources/js/components/FormInput.vue
  resources/js/components/pages/Collections.vue
  resources/js/components/pages/Tokens.vue
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#155 [PLA-1920] supply cap fix
  resources/js/components/ReadMoreButton.vue
  resources/js/components/pages/create/CreateToken.vue
Labels: enhancement, Bug fix, Review effort [1-5]: 2

#156 [PLA-1941] improve tracking check with wallet accounts
  resources/js/api/auth.ts
  resources/js/api/marketplace.ts
  resources/js/components/App.vue
  resources/js/components/MultiCheckbox.vue
  resources/js/components/SupportButton.vue
  resources/js/components/TrackCollectionModal.vue
  resources/js/components/WalletConnectButton.vue
  resources/js/components/pages/SettingsWalletAccount.vue
  resources/js/components/pages/Wallets.vue
  resources/js/components/pages/auth/Login.vue
  resources/js/components/pages/create/CreateCollection.vue
  resources/js/factory/collection.ts
  resources/js/graphql/mutation/TrackCollection.ts
  resources/js/graphql/mutation/UntrackCollection.ts
  resources/js/store/connection.ts
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#157 [PLA-1786] fix login text
  resources/js/store/index.ts
Labels: Review effort [1-5]: 2, bug_fix
