Repository enjin/platform-ui, pull requests merged in 2024-05, with the labels that each got.

#105 [PLA-1756] add claim conditions view
  resources/js/api/beam.ts
  resources/js/components/slideovers/beam/DetailsBeamSlideover.vue
  resources/js/components/slideovers/beam/UpdateBeamSlideover.vue
  resources/js/graphql/mutation/beam/UpdateBeam.ts
  resources/js/graphql/query/beam/GetBeam.ts
  resources/js/graphql/query/beam/GetBeams.ts
Labels: enhancement, Review effort [1-5]: 3, bug_fix

#106 [PLA-1758] fix fuel tank
  resources/js/components/slideovers/fueltank/ConsumptionFuelTankSlideover.vue
  resources/js/components/slideovers/fueltank/MutateFuelTankSlideover.vue
Labels: enhancement, Review effort [1-5]: 2, bug_fix

#107 [PLA-1762] form fixes
  config/enjin-platform-ui.php
  package-lock.json
  package.json
  resources/js/components/FormSelect.vue
  resources/js/components/batch/forms/BatchMintForm.vue
  resources/js/components/batch/forms/BatchTransferForm.vue
  resources/js/components/fueltank/DispatchRuleForm.vue
  resources/js/components/slideovers/beam/ClaimBeamSlideover.vue
  resources/js/components/slideovers/beam/UpdateBeamSlideover.vue
  resources/js/components/slideovers/common/DetailsTransactionSlideover.vue
  resources/js/components/slideovers/common/FreezeSlideover.vue
  resources/js/components/slideovers/common/ThawSlideover.vue
  resources/js/components/slideovers/fueltank/AccountsFuelTankSlideover.vue
  resources/js/components/slideovers/fueltank/ConsumptionFuelTankSlideover.vue
  resources/js/components/slideovers/fueltank/DispatchFuelTankSlideover.vue
  resources/js/components/slideovers/fueltank/FreezeFuelTankSlideover.vue
  resources/js/components/slideovers/fueltank/MutateFuelTankSlideover.vue
  resources/js/components/slideovers/fueltank/RuleSetsFuelTankSlideover.vue
  resources/js/components/slideovers/token/ApproveTokenSlideover.vue
  resources/js/components/slideovers/token/AttributesTokenSlideover.vue
  resources/js/components/slideovers/token/BurnTokenSlideover.vue
  resources/js/components/slideovers/token/MintTokenSlideover.vue
  resources/js/components/slideovers/token/MutateTokenSlideover.vue
  resources/js/components/slideovers/token/TransferTokenSlideover.vue
  resources/js/components/slideovers/token/UnapproveTokenSlideover.vue
  resources/js/store/index.ts
Labels: enhancement, Review effort [1-5]: 3, bug_fix

#103 [PLA-1731] text fixes
  resources/js/components/pages/create/CreateCollection.vue
  resources/js/components/pages/create/CreateToken.vue
Labels: enhancement, Review effort [1-5]: 3

#110 [PLA-1766] require password settings
  resources/js/api/auth.ts
  resources/js/components/Modal.vue
  resources/js/components/pages/Settings.vue
  resources/js/components/pages/SettingsChangeEmail.vue
  resources/js/components/pages/VerifyPasswordModal.vue
  resources/js/graphql/mutation/auth/DeleteAccount.ts
  resources/js/graphql/mutation/auth/UpdateUser.ts
  resources/js/router/index.ts
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#111 [PLA-1772] fix marketplace listing
  resources/js/api/marketplace.ts
  resources/js/api/queries.ts
  resources/js/components/Chip.vue
  resources/js/components/CollapseFilter.vue
  resources/js/components/Popover.vue
  resources/js/components/pages/create/CreateListing.vue
  resources/js/graphql/mutation/marketplace/CreateListing.ts
  resources/js/graphql/query/marketplace/GetBlocks.ts
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#112 [PLA-1773] fix wallet and beam query
  resources/js/api/beam.ts
  resources/js/api/index.ts
  resources/js/api/queries.ts
  resources/js/api/transaction.ts
  resources/js/components/beam/BeamsList.vue
  resources/js/components/beam/ClaimsList.vue
  resources/js/components/marketplace/BidsList.vue
  resources/js/components/marketplace/ListingsList.vue
  resources/js/components/marketplace/SalesList.vue
  resources/js/components/pages/Collections.vue
  resources/js/components/pages/FuelTanks.vue
  resources/js/components/pages/Tokens.vue
  resources/js/components/pages/Transactions.vue
  resources/js/components/pages/Wallets.vue
  resources/js/components/pages/auth/Login.vue
  resources/js/components/pages/create/CreateBeam.vue
  resources/js/factory/wallet.ts
  resources/js/graphql/query/GetWallets.ts
  resources/js/graphql/query/beam/GetBeam.ts
  resources/js/graphql/query/beam/GetBeams.ts
  resources/js/graphql/query/beam/GetSingleUseCodes.ts
  resources/js/store/index.ts
  resources/js/types/types.interface.ts
Labels: enhancement, Bug fix, Review effort [1-5]: 4

#113 [PLA-1417] Add element dusk id
  resources/js/components/ConfirmModal.vue
  resources/js/components/FormDateInput.vue
  resources/js/components/FormSelect.vue
  resources/js/components/beam/BeamsList.vue
  resources/js/components/beam/ClaimsList.vue
  resources/js/components/fueltank/DispatchRuleForm.vue
  resources/js/components/marketplace/BidsList.vue
  resources/js/components/marketplace/ListingsList.vue
  resources/js/components/marketplace/SalesList.vue
  resources/js/components/pages/FuelTanks.vue
  resources/js/components/pages/Transactions.vue
  resources/js/components/pages/Wallets.vue
  resources/js/components/pages/create/CreateBeam.vue
  resources/js/components/pages/create/CreateFuelTank.vue
  resources/js/components/slideovers/beam/ClaimBeamSlideover.vue
  resources/js/components/slideovers/common/RetryTransactionSlideover.vue
Labels: enhancement, Review effort [1-5]: 2

#115 [PLA-1781] update password query
  resources/js/components/pages/VerifyPasswordModal.vue
  resources/js/store/index.ts
Labels: enhancement, Bug fix, Review effort [1-5]: 2

#114 [PLA-1417] Add dusk id
  resources/js/components/pages/VerifyPasswordModal.vue
Labels: enhancement, Review effort [1-5]: 2

#116 hotfix: clear promise call
  resources/js/components/beam/BeamsList.vue
  resources/js/components/beam/ClaimsList.vue
  resources/js/components/marketplace/BidsList.vue
  resources/js/components/marketplace/ListingsList.vue
  resources/js/components/marketplace/SalesList.vue
  resources/js/components/pages/Collections.vue
  resources/js/components/pages/FuelTanks.vue
  resources/js/components/pages/Tokens.vue
  resources/js/components/pages/Transactions.vue
  resources/js/components/pages/Wallets.vue
  resources/js/components/pages/auth/Login.vue
  resources/js/store/index.ts
Labels: Bug fix, Review effort [1-5]: 2

#117 [PLA-1785] remove init promise
  resources/js/components/App.vue
  resources/js/components/beam/BeamsList.vue
  resources/js/components/beam/ClaimsList.vue
  resources/js/components/marketplace/BidsList.vue
  resources/js/components/marketplace/ListingsList.vue
  resources/js/components/marketplace/SalesList.vue
  resources/js/components/pages/Collections.vue
  resources/js/components/pages/FuelTanks.vue
  resources/js/components/pages/Tokens.vue
  resources/js/components/pages/Transactions.vue
  resources/js/components/pages/Wallets.vue
  resources/js/components/pages/auth/Login.vue
  resources/js/store/index.ts
Labels: enhancement, Bug fix, Review effort [1-5]: 3
