Repository enjin/platform-ui, pull requests merged in 2025-03, with the labels that each got.

#195 [PLA-2209] set transaction era
  resources/js/graphql/query/GetTransaction.ts
  resources/js/graphql/query/GetTransactions.ts
  resources/js/store/transaction.ts
Labels: Review effort 2/5

#196 [PLA-2209] add mode and metadataHash to transaction
  resources/js/store/transaction.ts
Labels: Review effort 1/5

#197 [PLA-2209] Adds mortality to transactions on WC
  resources/js/store/transaction.ts
Labels: Review effort 2/5

#198 [PLA-2149] fueltank fix
  resources/js/components/FormCheckbox.vue
  resources/js/components/FormInput.vue
  resources/js/components/RadioInput.vue
  resources/js/components/fueltank/DispatchRuleForm.vue
  resources/js/components/slideovers/fueltank/DispatchFuelTankSlideover.vue
Labels: Review effort 3/5

#199 [PLA-2141] fix searched collections
  resources/js/components/pages/Collections.vue
Labels: Review effort 3/5

#200 [PLA-2222] fix polkadotjs transaction
  package-lock.json
  package.json
  resources/js/components/App.vue
  resources/js/components/ThemeToggler.vue
  resources/js/components/pages/SettingsWalletDaemon.vue
  resources/js/store/transaction.ts
Labels: Review effort 3/5
