Repository enjin/platform-ui, pull requests merged in 2025-01, with the labels that each got.

#185 [PLA-3113] remove required image from batch mint
  resources/js/components/batch/forms/BatchMintForm.vue
Labels: Review effort [1-5]: 1

#186 [PLA-2075] [PLA-1856] [PLA-2129] [PLA-2081] [PLA-1918] bug fixes
  resources/js/components/FormSelect.vue
  resources/js/components/beam/ClaimsList.vue
  resources/js/components/pages/Collections.vue
  resources/js/components/pages/FuelTanks.vue
  resources/js/components/slideovers/beam/ClaimBeamSlideover.vue
  resources/js/components/slideovers/fueltank/DetailsFuelTankSlideover.vue
  resources/js/components/slideovers/fueltank/FreezeFuelTankSlideover.vue
  resources/js/components/slideovers/token/BurnTokenSlideover.vue
  resources/js/util/index.ts
Labels: Review effort [1-5]: 4

#187 feat: PLA-284 Add Metamask snap support
  package-lock.json
  package.json
  resources/js/api/index.ts
  resources/js/components/WalletConnectButton.vue
  resources/js/store/connection.ts
  resources/js/store/transaction.ts
Labels: Review effort [1-5]: 4

#188 fix: walletName for MetaMask
  resources/js/components/WalletConnectButton.vue
  resources/js/components/pages/SettingsWalletApp.vue
Labels: Review effort [1-5]: 2

#190 [PLA-2141] fix collection query
  resources/js/api/collection.ts
  resources/js/components/pages/Collections.vue
  resources/js/graphql/query/GetCollections.ts
Labels: Review effort [1-5]: 3

#189 [PLA-2149] [PLA-1923] fueltank fix
  resources/js/api/fueltank.ts
  resources/js/components/FormCheckbox.vue
  resources/js/components/FormSelect.vue
  resources/js/components/InputHeader.vue
  resources/js/components/MultiCheckbox.vue
  resources/js/components/RadioGroupButton.vue
  resources/js/components/RadioInput.vue
  resources/js/components/SupportButton.vue
  resources/js/components/fueltank/DispatchRuleForm.vue
  resources/js/components/pages/create/CreateFuelTank.vue
  resources/js/components/slideovers/fueltank/DetailsFuelTankSlideover.vue
  resources/js/components/slideovers/fueltank/DispatchFuelTankSlideover.vue
  resources/js/components/slideovers/fueltank/MutateFuelTankSlideover.vue
  resources/js/graphql/mutation/fueltank/CreateFuelTank.ts
  resources/js/graphql/query/fueltank/GetFuelTank.ts
  resources/js/graphql/query/fueltank/GetFuelTanks.ts
  resources/js/types/types.enums.ts
Labels: Review effort [1-5]: 4

#191 [PLA-2150] fix login connection
  resources/js/components/App.vue
  resources/js/store/index.ts
Labels: Review effort [1-5]: 3

#192 PLA-2153 bump metamask-enjin-adapter to 0.1.2
  package-lock.json
  package.json
Labels: Review effort [1-5]: 1

#193 [PLA-2156] fix wallet session
  resources/js/store/connection.ts
Labels: Review effort [1-5]: 2
